String today= 'Monday';

switch on today{
    when 'Monday','Saturday'{
        System.debug('Dia da semana: ' + today);
    }
    when 'Tuesday'{
        System.debug('Dia da semana: ' + today);
    }
    when 'Wednesday'{
        System.debug('Dia da semana: ' + today);
    }
    when 'Thursday'{
        System.debug('Dia da semana: ' + today);
    }
    when 'Friday'{
        System.debug('Dia da semana: ' + today);
}
}